"""
build-scripts/generate_api_types.py — Pydantic → TypeScript codegen.

Layer C5 of the architectural plan. Walks ``backend/routes/*.py``,
collects every ``BaseModel`` subclass, and emits a single TS declaration
file at ``desktop-ui/api/generated.d.ts`` containing the equivalent
interfaces. Wired into CI so a Pydantic change that's not reflected in
the renderer's hand-typed request shapes is caught at PR time instead
of at integration time.

Why a custom collector instead of just pointing pydantic2ts at a single
module? The 56 BaseModels live across 13 route files
(``routes/chat.py``, ``routes/settings.py``, …) — pydantic2ts wants
one module path. We write a small index module that re-exports every
BaseModel under a stable name, then hand THAT to pydantic2ts.

Run locally:
    python build-scripts/generate_api_types.py

CI fails when the regenerated file would change. Operators regenerate
locally and commit the diff alongside the underlying Pydantic edit.

The set of source modules is intentionally allowlisted (``_SOURCE_MODULES``)
rather than auto-discovered, so adding a new BaseModel to a route file
that should NOT be exposed to the renderer (e.g. internal validation
helpers) is a deliberate one-line edit, not an accidental schema leak.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import sys
import tempfile
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
DEFAULT_OUTPUT = REPO_ROOT / "desktop-ui" / "api" / "generated.d.ts"

# Allowlist: every route module that contains request/response Pydantic
# models the renderer needs to know about. Add a module here when you
# add a new route file with BaseModels the frontend will POST to. Skip
# modules whose models are purely server-internal.
_SOURCE_MODULES: tuple[str, ...] = (
    "routes.agents",
    "routes.chat",
    "routes.docker",
    "routes.echo",
    "routes.lifecycle",
    "routes.mcp",
    "routes.memory",
    "routes.prompt_templates",
    "routes.prompts",
    "routes.rag",
    "routes.settings",
    "routes.system",
    "routes.voice",
)


def _collect_models() -> list[type]:
    """Return every concrete BaseModel subclass defined directly in the
    allowlisted route modules. Models inherited from pydantic itself or
    re-imported from elsewhere are skipped — we only want classes
    *declared* in the routes layer."""
    sys.path.insert(0, str(BACKEND_DIR))
    from pydantic import BaseModel

    seen: dict[str, type] = {}
    for dotted in _SOURCE_MODULES:
        module = importlib.import_module(dotted)
        for name, obj in inspect.getmembers(module, inspect.isclass):
            if obj is BaseModel:
                continue
            if not issubclass(obj, BaseModel):
                continue
            if obj.__module__ != module.__name__:
                # Re-imported from somewhere else (e.g. ``from pydantic
                # import BaseModel``). Skip — we only codegen the ones
                # the route module *defines*.
                continue
            if name in seen and seen[name] is not obj:
                raise RuntimeError(
                    f"Pydantic class name collision: {name!r} is defined in both "
                    f"{seen[name].__module__} and {obj.__module__}. Rename one before "
                    f"running the codegen — TS doesn't namespace by source module.",
                )
            seen[name] = obj
    return [seen[name] for name in sorted(seen)]


def _write_index_module(models: list[type], dest: Path) -> None:
    """Emit a synthetic Python file that imports every collected model so
    pydantic2ts can point at one file. The file is throwaway — pydantic2ts
    reads it once, discovers the models via inspect.getmembers, and emits
    the TS."""
    lines = [
        '"""',
        "AUTO-GENERATED by build-scripts/generate_api_types.py — do not edit.",
        "Synthetic index module that re-exports every routes-layer Pydantic",
        "BaseModel so pydantic2ts has a single discovery target.",
        '"""',
        "",
    ]
    # Group imports by source module so the file is human-readable on
    # the rare occasion someone opens it during a CI failure.
    by_module: dict[str, list[str]] = {}
    for model in models:
        by_module.setdefault(model.__module__, []).append(model.__name__)
    for module_name in sorted(by_module):
        names = sorted(by_module[module_name])
        lines.append(f"from {module_name} import {', '.join(names)}")
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")


_HEADER = textwrap.dedent("""\
    /**
     * AUTO-GENERATED by build-scripts/generate_api_types.py — do not edit.
     *
     * Pydantic request/response models from backend/routes/*.py translated
     * into TypeScript interfaces. The CI gate in .github/workflows/tests.yml
     * re-runs the codegen on every PR and fails if this file would change
     * — keep it in sync by regenerating locally:
     *
     *     python build-scripts/generate_api_types.py
     *
     * Then commit the diff alongside the underlying Pydantic change.
     */
""")


def _prepend_header(output: Path) -> None:
    """Prepend our human-readable banner above whatever pydantic2ts /
    json-schema-to-typescript emit. Their default banner says ``This file
    was automatically generated`` but doesn't mention HOW to regenerate
    — the operator confusion that causes is the one thing we can fix
    in a one-line preamble."""
    body = output.read_text(encoding="utf-8")
    # Strip the json-schema-to-typescript banner if present so we don't
    # have two banners stacked. It always starts with /* tslint:disable */
    # or /* eslint-disable */ followed by the upstream comment block.
    output.write_text(_HEADER + "\n" + body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="Path to write the generated .d.ts (default: %(default)s)",
    )
    parser.add_argument(
        "--json2ts-cmd", default="npx --no-install json2ts",
        help=(
            "Command to invoke json-schema-to-typescript. Default uses "
            "the locally-installed npm package; CI uses the same after "
            "`npm ci`."
        ),
    )
    args = parser.parse_args(argv)

    models = _collect_models()
    if not models:
        sys.stderr.write(
            "No Pydantic models discovered. Check _SOURCE_MODULES in this "
            "script — the route allowlist must point at the right modules.\n"
        )
        return 1

    from pydantic2ts import generate_typescript_defs

    with tempfile.TemporaryDirectory() as tmpdir:
        index_path = Path(tmpdir) / "_codegen_index.py"
        _write_index_module(models, index_path)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        generate_typescript_defs(
            module=str(index_path),
            output=str(args.output),
            json2ts_cmd=args.json2ts_cmd,
        )

    _prepend_header(args.output)
    print(f"Wrote {len(models)} interfaces to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
