/**
 * AUTO-GENERATED by build-scripts/generate_api_types.py — do not edit.
 *
 * Pydantic request/response models from backend/routes/*.py translated
 * into TypeScript interfaces. The CI gate in .github/workflows/tests.yml
 * re-runs the codegen on every PR and fails if this file would change
 * — keep it in sync by regenerating locally:
 *
 *     python build-scripts/generate_api_types.py
 *
 * Then commit the diff alongside the underlying Pydantic change.
 */

/* tslint:disable */
/* eslint-disable */
/**
/* This file was automatically generated from pydantic models by running pydantic2ts.
/* Do not modify it by hand - just update the pydantic models and then re-run the script
*/

export interface ActiveLocalModelIn {
  model_id: string;
}
export interface AgentCreateIn {
  name: string;
  description: string;
  system_prompt: string;
  model_preference?: string;
  temperature?: number;
  max_tokens?: number;
}
export interface AgentDuplicateIn {
  agent_id: string;
  new_name: string;
}
export interface AgentProjectRootIn {
  path: string;
}
export interface AgentTomIn {
  agent_name: string;
  agent_domain: string;
  agent_scope: string;
  teammates?: unknown[] | null;
}
export interface AgentUpdateIn {
  agent_id: string;
  fields: {
    [k: string]: unknown;
  };
}
export interface ApproveIn {
  task_id: string;
  approval_id: string;
  allow: boolean;
}
export interface AssetsDownloadIn {
  stt_model_id?: string;
  tts_voice_id?: string;
}
export interface BundledDownloadIn {
  model_id?: string;
}
export interface BundledStartIn {
  model_id?: string;
}
export interface CancelIn {
  task_id: string;
}
export interface ChatBranchIn {
  conversation_id: string;
  from_message_id: string;
}
export interface ChatExportIn {
  conversation_id: string;
  fmt?: string;
}
export interface ChatNewIn {
  agent_id?: string;
  title?: string;
}
export interface ChatRenameIn {
  conversation_id: string;
  title: string;
}
export interface ChatSendIn {
  conversation_id: string;
  user_message: string;
  agent_id?: string;
}
export interface ChatStopIn {
  conversation_id?: string;
}
export interface ChatThinkingIn {
  user_message: string;
  budget_tokens?: number;
}
export interface ClassifyIn {
  user_message: string;
  conversation_id?: string;
}
export interface DocumentSearchIn {
  query: string;
  top_k?: number;
  doc_type?: string;
}
export interface EchoIn {
  text: string;
}
export interface EchoOut {
  text: string;
  reversed: string;
}
export interface EnabledIn {
  server_id: string;
  enabled: boolean;
}
export interface ExecuteIn {
  conversation_id: string;
  user_message: string;
}
export interface FetchModelsIn {
  backend: string;
}
export interface FileIn {
  file_path: string;
}
export interface FirewallIn {
  enabled: boolean;
}
export interface FirstRunIn {
  start_tab: string;
}
export interface FolderIn {
  folder_path: string;
}
export interface HealthCheckIn {
  skip_api?: boolean;
}
export interface HybridSearchIn {
  query: string;
  top_k?: number;
  method?: string;
  doc_type?: string;
}
export interface IngestFolderIn {
  folder_path: string;
  overwrite?: boolean;
}
export interface KVIn {
  key: string;
  value: unknown;
}
export interface OpenUrlIn {
  url: string;
}
export interface PricesIn {
  prices: {
    [k: string]: unknown;
  };
}
export interface PromptCreateIn {
  name: string;
  category: string;
  description: string;
  text: string;
  model_target?: string;
}
export interface PromptDuplicateIn {
  source_id: string;
  new_name: string;
}
export interface PromptImportIn {
  data: {
    [k: string]: unknown;
  };
}
export interface PromptRestoreIn {
  version_id: string;
}
export interface PromptSaveIn {
  prompt_id: string;
  text: string;
  notes?: string;
}
export interface PromptTemplateCreate {
  title: string;
  body: string;
  kind: "snippet" | "system_prompt";
  tags?: string | null;
}
export interface PromptTemplateOut {
  id: string;
  title: string;
  body: string;
  kind: string;
  tags: string;
  created_at: string;
  updated_at: string;
  use_count: number;
}
export interface PromptTemplateUpdate {
  title?: string | null;
  body?: string | null;
  kind?: ("snippet" | "system_prompt") | null;
  tags?: string | null;
}
export interface SaveMemoryIn {
  content: string;
  category?: string;
}
export interface SearchIn {
  query: string;
  top_k?: number;
}
export interface SecretIn {
  server_id: string;
  key: string;
  value?: string;
}
export interface SemanticSearchIn {
  query: string;
  top_k?: number;
}
export interface ShutdownDemoIn {
  target_id?: string;
  requester_id?: string;
  reason?: string;
}
export interface StudioModeIn {
  enabled: boolean;
}
export interface SynthesizeIn {
  text: string;
  voice_id?: string;
}
export interface TeamCreateIn {
  name: string;
  description: string;
  coordinator_id: string;
}
export interface TeamMemberIn {
  team_id: string;
  agent_id: string;
  role?: string;
}
export interface TestConnIn {
  backend: string;
}
export interface TextIn {
  text: string;
  source?: string;
}
export interface TokenIn {
  token: string;
}
export interface VerifyKeyIn {
  key: string;
}
